# Generated by Django 5.2.17 on 2026-10-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.CharField(max_length=32, unique=True)),
                ('robot_id', models.CharField(max_length=32)),
                ('task_name', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('operator_name', models.CharField(blank=True, max_length=100)),
                ('quality', models.CharField(choices=[('good', 'Good'), ('usable', 'Usable'), ('bad', 'Bad')], max_length=8)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at', 'episode_id'],
                'indexes': [models.Index(fields=['recorded_at', 'robot_id'], name='episode_recorded_robot_idx'), models.Index(fields=['quality', 'task_name', 'recorded_at'], name='episode_quality_task_idx'), models.Index(fields=['task_name'], name='episode_task_idx')],
            },
        ),
    ]
